{
 "title": "MyChat Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MySQL Up",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 5 },
   "targets": [
    { "expr": "mychat_mysql_up" }
   ]
  },
  {
   "title": "Redis Up",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 5 },
   "targets": [
    { "expr": "mychat_redis_up" }
   ]
  },
  {
   "title": "ChatServer Listen",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 5 },
   "targets": [
    { "expr": "mychat_chatserver_listen" }
   ]
  },
  {
   "title": "TCP Established",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 5 },
   "targets": [
    {
     "expr": "mychat_chatserver_tcp_established"
    }
   ]
  },
  {
   "title": "Core DB Table Size",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 24, "h": 9 },
   "targets": [
    { "expr": "mychat_db_user_total", "legendFormat": "user" },
    { "expr": "mychat_db_friend_total", "legendFormat": "friend" },
    { "expr": "mychat_db_group_total", "legendFormat": "group" },
    { "expr": "mychat_db_groupuser_total", "legendFormat": "groupuser" },
    { "expr": "mychat_db_offline_total", "legendFormat": "offline" }
   ]
  }
 ]
}